import Banner from "../../components/Banner";
import Header from "../../components/Header";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Blink Blog",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true} className="max-w-7xl m-auto">
                <Header />
                <Banner />
                {children}
            </body>
        </html>
    );
}
